"""
Root Cause Synthesizer - Agent #9 
Cross-correlates findings from all 6 domain analysts, ranks root causes,
and generates actionable recommendations.

Does not call Cube.js - only processes the findings from other agents. 
FLOW: All 6 RCA analysts (parallel) -> Synthsizer -> Response

"""

import json 
import os 
from langchain_openai import AzureChatOpenAI
from agents.state import ChatState, RankedCause

llm = AzureChatOpenAI(
    azure_deployment = os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME"),
    azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT"),
    api_key = os.getenv("AZURE_OPENAI_API_KEY"),
    api_version = os.getenv("AZURE_OPENAI_API_VERSION"),
    temperature = 0
)

SYNTHESIZER_PROMPT = """You are a senior retail analytics lead. 6 domain analysts have independently investigated
a store performance issue and produced findings.

Your job is to:
1. CORRELATE: Find timing and causal links across findings
2. CORROBORATE: Note when multiple analysts point to the same cause
3. RANK: Order root causes by ( impact x confidence x controllability )
4. RECOMMEND: Give specific, actionable recommendations for each cause

USER QUESTION = {user_query}
ANALYST FINDINGS:
{findings}

RESPOND IN THIS JSON FORMAT:
{{
    "root_causes":[
    {{
    
    
        "rank":1,
        "cause": "Clear description of root cause",
        "category": "traffic|sales|promo|inventory|customer|external",
        "severity": "high|medium|low",
        "confidence":"high|medium|low",
        "evidence": ["evidence from analyst 1", "corooboration evidence from analyst 2"],
        "recommendation": "Specific action to take",
        "controllability": "high|medium|low"
    
    }}],
    "summary": "2-3 sentence executive summary of the overall situation"
}}

RANKING RULES:
- High impact + high confidence + high controllability = rank higher
- Causes corroborated by multiple analysts = boost confidence
- External/uncontrollable cause ranked lower unless very high impact
- Maximum 5 root causes (focus on the most important ones)


"""


async def synthesizer_node( state: ChatState) -> dict:
    print("Running: Synthesizer Agent....")
    user_query = state["user_query"]
    findings = state.get("findings",[])

    if not findings: 
        return {
            "root_causes": [],
            "response": "No findings were generated by the analyst agents. There may not be enough data to perform a root cause analysis for this query.",

        }
    findings_text = json.dumps(findings, indent =2 , default = str)

    response = await llm.ainvoke([
        {
            "role":"system", 
            "content": SYNTHESIZER_PROMPT.format(
                user_query = user_query,
                findings = findings_text,
            )
        },
        {
            "role": "user",
            "content":"Synthesize the findings and rank root causes."
        },
    ])

    try:
        result = json.loads(response.content)

    except json.JSONDecodeError:
        return {
            "root_causes": [],
            "response": response.content,
        }

    root_causes= []

    for rc in result.get("root_causes",[]):
        root_causes.append(RankedCause(
            rank= rc.get("rank",0),
            cause = rc.get("cause", ""),
            category = rc.get("category",""),
            severity = rc.get("severity","low"),
            confidence = rc.get("confidence","low"),
            evidence = rc.get("evidence",[]),
            recommendation = rc.get('recommendation',""),
        ))

    return {
        "root_causes": root_causes
    }